[build]
  publish = "build"

# إعدادات إعادة التوجيه للويب هوك
[[redirects]]
  from = "/api/contact"
  to = "https://cloud.activepieces.com/api/v1/webhooks/O4RKo8kmQwsTORFYUZzm9"
  status = 200
  force = true
  headers = {X-Frame-Options = "DENY", X-XSS-Protection = "1; mode=block"}

# إعادة التوجيه للصفحات غير الموجودة (SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
